Second Homework
ohmykir/sber-practice-java pull request #3
Opened 2024-03-18 21:51 UTC by ohmykir

OOP

2024-03-27 15:03 UTC, XLelarX requested changes

2024-03-27 15:03 UTC, XLelarX commented on OOP/src/test/java/com/test/PhoneTest.java
> +        assertEquals("Звонит: Коля\r\nЗвонит: Петя (88005553535)", outputStreamCaptor.toString().trim());
Можешь глянуть в метод String.format(). Он позволяет задать паттерн для строк.

2024-03-27 15:03 UTC, XLelarX commented on OOP/src/test/java/com/test/PhoneTest.java
> +        System.setOut(standardOut);
Выглядит лишним  System.setOut() во всем коде

2024-03-27 15:03 UTC, XLelarX commented on OOP/src/test/java/com/test/PizzaOrderTest.java
> +        assertEquals("Заказ отменен.", outputStreamCaptor.toString().trim());
Я заметил что у тебя сравнение объектов происходит только через toString(). Так делать не обязательно, можно сравнивать объекты напрямую assertEquals(object1, object2). Только нужно чтоб equals был реализован

2024-03-27 20:00 UTC, ohmykir commented on OOP/src/test/java/com/test/PhoneTest.java
> +        System.setOut(standardOut);
Ну без этого тесты падают (и того, что в начале), а как еще void методы тестировать, я не нашел

2024-03-27 20:00 UTC, ohmykir commented on OOP/src/test/java/com/test/PizzaOrderTest.java
> +        assertEquals("Заказ отменен.", outputStreamCaptor.toString().trim());
Это типа тест метода toString, потому что еще тестить в некоторых классах, я не знаю. Не геттеры, сеттеры ведь

2024-04-01 18:01 UTC, XLelarX commented on OOP/src/test/java/com/test/PhoneTest.java
> +        System.setOut(standardOut);
Для void методов нужно чтоб внутренняя логика отрабатывала определенным образом, те это делается при помощи verify методов. Но придумано хитро, так что если не хочешь разбираться как это переписать через verify, то можно забить)

2024-04-01 18:41 UTC, XLelarX approved these changes

2024-04-01 18:41 UTC, merged